/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jd522.main;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class Main_frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_frame() {
        initComponents();
        // Set focus to another component
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                registerTitleLbl.requestFocusInWindow();
            }
        });
        
    }

    formativeLogin myObj = new formativeLogin();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckRegisterLP = new javax.swing.JLayeredPane();
        registerTitleLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        registerUserLP = new javax.swing.JLayeredPane();
        registerUserTxtField = new javax.swing.JTextField();
        registerPasswordLP = new javax.swing.JLayeredPane();
        registerPasswordTxtField = new javax.swing.JTextField();
        registerFirstNameLP = new javax.swing.JLayeredPane();
        registerFirstNameTxtField = new javax.swing.JTextField();
        registerLastNameLP = new javax.swing.JLayeredPane();
        registerLastNameTxtField = new javax.swing.JTextField();
        loginTitleLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        loginUserLP = new javax.swing.JLayeredPane();
        loginUserLbl = new javax.swing.JLabel();
        loginUserTxtField = new javax.swing.JTextField();
        loginPasswordLP = new javax.swing.JLayeredPane();
        loginPasswordTxtField = new javax.swing.JLabel();
        loginPasswordPswField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(933, 537));

        bckRegisterLP.setBackground(new java.awt.Color(0, 204, 153));
        bckRegisterLP.setOpaque(true);
        bckRegisterLP.setPreferredSize(new java.awt.Dimension(450, 100));

        registerTitleLbl.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        registerTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        registerTitleLbl.setText("Create Account");

        registerBtn.setBackground(new java.awt.Color(204, 204, 204));
        registerBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 0, 0));
        registerBtn.setText("REGISTER");
        registerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        registerBtn.setBorderPainted(false);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        registerUserLP.setBackground(new java.awt.Color(255, 255, 255));
        registerUserLP.setOpaque(true);
        registerUserLP.setPreferredSize(new java.awt.Dimension(105, 17));

        registerUserTxtField.setBackground(new java.awt.Color(255, 255, 255));
        registerUserTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerUserTxtField.setForeground(new java.awt.Color(153, 153, 153));
        registerUserTxtField.setText("Enter Username");
        registerUserTxtField.setBorder(null);
        registerUserTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerUserTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerUserTxtFieldFocusLost(evt);
            }
        });

        registerUserLP.setLayer(registerUserTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout registerUserLPLayout = new javax.swing.GroupLayout(registerUserLP);
        registerUserLP.setLayout(registerUserLPLayout);
        registerUserLPLayout.setHorizontalGroup(
            registerUserLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerUserLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerUserTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
        registerUserLPLayout.setVerticalGroup(
            registerUserLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerUserTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        registerPasswordLP.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordLP.setOpaque(true);
        registerPasswordLP.setPreferredSize(new java.awt.Dimension(105, 17));

        registerPasswordTxtField.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerPasswordTxtField.setForeground(new java.awt.Color(153, 153, 153));
        registerPasswordTxtField.setText("Enter Password");
        registerPasswordTxtField.setBorder(null);
        registerPasswordTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerPasswordTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerPasswordTxtFieldFocusLost(evt);
            }
        });

        registerPasswordLP.setLayer(registerPasswordTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout registerPasswordLPLayout = new javax.swing.GroupLayout(registerPasswordLP);
        registerPasswordLP.setLayout(registerPasswordLPLayout);
        registerPasswordLPLayout.setHorizontalGroup(
            registerPasswordLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPasswordLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerPasswordTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
        registerPasswordLPLayout.setVerticalGroup(
            registerPasswordLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPasswordTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        registerFirstNameLP.setBackground(new java.awt.Color(255, 255, 255));
        registerFirstNameLP.setOpaque(true);
        registerFirstNameLP.setPreferredSize(new java.awt.Dimension(105, 17));

        registerFirstNameTxtField.setBackground(new java.awt.Color(255, 255, 255));
        registerFirstNameTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerFirstNameTxtField.setForeground(new java.awt.Color(153, 153, 153));
        registerFirstNameTxtField.setText("Enter First Name");
        registerFirstNameTxtField.setBorder(null);
        registerFirstNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerFirstNameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerFirstNameTxtFieldFocusLost(evt);
            }
        });

        registerFirstNameLP.setLayer(registerFirstNameTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout registerFirstNameLPLayout = new javax.swing.GroupLayout(registerFirstNameLP);
        registerFirstNameLP.setLayout(registerFirstNameLPLayout);
        registerFirstNameLPLayout.setHorizontalGroup(
            registerFirstNameLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerFirstNameLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerFirstNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
        registerFirstNameLPLayout.setVerticalGroup(
            registerFirstNameLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerFirstNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        registerLastNameLP.setBackground(new java.awt.Color(255, 255, 255));
        registerLastNameLP.setOpaque(true);
        registerLastNameLP.setPreferredSize(new java.awt.Dimension(105, 17));

        registerLastNameTxtField.setBackground(new java.awt.Color(255, 255, 255));
        registerLastNameTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerLastNameTxtField.setForeground(new java.awt.Color(153, 153, 153));
        registerLastNameTxtField.setText("Enter Last Name");
        registerLastNameTxtField.setBorder(null);
        registerLastNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerLastNameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerLastNameTxtFieldFocusLost(evt);
            }
        });

        registerLastNameLP.setLayer(registerLastNameTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout registerLastNameLPLayout = new javax.swing.GroupLayout(registerLastNameLP);
        registerLastNameLP.setLayout(registerLastNameLPLayout);
        registerLastNameLPLayout.setHorizontalGroup(
            registerLastNameLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerLastNameLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLastNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
        registerLastNameLPLayout.setVerticalGroup(
            registerLastNameLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLastNameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        bckRegisterLP.setLayer(registerTitleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bckRegisterLP.setLayer(registerBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bckRegisterLP.setLayer(registerUserLP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bckRegisterLP.setLayer(registerPasswordLP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bckRegisterLP.setLayer(registerFirstNameLP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bckRegisterLP.setLayer(registerLastNameLP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bckRegisterLPLayout = new javax.swing.GroupLayout(bckRegisterLP);
        bckRegisterLP.setLayout(bckRegisterLPLayout);
        bckRegisterLPLayout.setHorizontalGroup(
            bckRegisterLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bckRegisterLPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerTitleLbl)
                .addGap(105, 105, 105))
            .addGroup(bckRegisterLPLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(bckRegisterLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLastNameLP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerFirstNameLP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPasswordLP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserLP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        bckRegisterLPLayout.setVerticalGroup(
            bckRegisterLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bckRegisterLPLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(registerTitleLbl)
                .addGap(62, 62, 62)
                .addComponent(registerUserLP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerPasswordLP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerFirstNameLP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerLastNameLP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        loginTitleLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginTitleLbl.setForeground(new java.awt.Color(0, 204, 153));
        loginTitleLbl.setText("Welcome Back!");
        loginTitleLbl.setPreferredSize(new java.awt.Dimension(184, 35));

        loginBtn.setBackground(new java.awt.Color(0, 204, 153));
        loginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 1, true));
        loginBtn.setBorderPainted(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginUserLP.setBackground(new java.awt.Color(255, 255, 255));
        loginUserLP.setForeground(new java.awt.Color(0, 0, 0));
        loginUserLP.setOpaque(true);
        loginUserLP.setPreferredSize(new java.awt.Dimension(100, 38));

        loginUserLbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginUserLbl.setForeground(new java.awt.Color(153, 153, 153));
        loginUserLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jd522.icon/user.png"))); // NOI18N
        loginUserLbl.setText(" Username:");

        loginUserTxtField.setBackground(new java.awt.Color(255, 255, 255));
        loginUserTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginUserTxtField.setForeground(new java.awt.Color(153, 153, 153));
        loginUserTxtField.setText("Enter Username");
        loginUserTxtField.setBorder(null);
        loginUserTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUserTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUserTxtFieldFocusLost(evt);
            }
        });

        loginUserLP.setLayer(loginUserLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginUserLP.setLayer(loginUserTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginUserLPLayout = new javax.swing.GroupLayout(loginUserLP);
        loginUserLP.setLayout(loginUserLPLayout);
        loginUserLPLayout.setHorizontalGroup(
            loginUserLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginUserLPLayout.createSequentialGroup()
                .addComponent(loginUserLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUserTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );
        loginUserLPLayout.setVerticalGroup(
            loginUserLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginUserLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loginUserTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(loginUserLbl))
        );

        loginPasswordLP.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordLP.setForeground(new java.awt.Color(0, 0, 0));
        loginPasswordLP.setOpaque(true);
        loginPasswordLP.setPreferredSize(new java.awt.Dimension(100, 38));

        loginPasswordTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginPasswordTxtField.setForeground(new java.awt.Color(153, 153, 153));
        loginPasswordTxtField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jd522.icon/pass.png"))); // NOI18N
        loginPasswordTxtField.setText("Password:");

        loginPasswordPswField.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordPswField.setForeground(new java.awt.Color(51, 51, 51));
        loginPasswordPswField.setBorder(null);

        loginPasswordLP.setLayer(loginPasswordTxtField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPasswordLP.setLayer(loginPasswordPswField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginPasswordLPLayout = new javax.swing.GroupLayout(loginPasswordLP);
        loginPasswordLP.setLayout(loginPasswordLPLayout);
        loginPasswordLPLayout.setHorizontalGroup(
            loginPasswordLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPasswordLPLayout.createSequentialGroup()
                .addComponent(loginPasswordTxtField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordPswField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
        );
        loginPasswordLPLayout.setVerticalGroup(
            loginPasswordLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPasswordLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loginPasswordPswField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(loginPasswordTxtField))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(loginTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginUserLP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginPasswordLP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(bckRegisterLP, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckRegisterLP, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loginTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(loginUserLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerUserTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserTxtFieldFocusGained
        // TODO add your handling code here:
        if (registerUserTxtField.getText().equals("Enter Username")) {
            registerUserTxtField.setText("");
            registerUserTxtField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_registerUserTxtFieldFocusGained

    private void registerUserTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserTxtFieldFocusLost
        // TODO add your handling code here:
        if (registerUserTxtField.getText().equals("")) {
            registerUserTxtField.setText("Enter Username");
            registerUserTxtField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_registerUserTxtFieldFocusLost

    private void registerPasswordTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordTxtFieldFocusGained
        // TODO add your handling code here:
        if (registerPasswordTxtField.getText().equals("Enter Password")) {
            registerPasswordTxtField.setText("");
            registerPasswordTxtField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_registerPasswordTxtFieldFocusGained

    private void registerPasswordTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordTxtFieldFocusLost
        // TODO add your handling code here:
        if (registerPasswordTxtField.getText().equals("")) {
            registerPasswordTxtField.setText("Enter Password");
            registerPasswordTxtField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_registerPasswordTxtFieldFocusLost

    private void registerFirstNameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFirstNameTxtFieldFocusGained
        // TODO add your handling code here:
        if (registerFirstNameTxtField.getText().equals("Enter First Name")) {
            registerFirstNameTxtField.setText("");
            registerFirstNameTxtField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_registerFirstNameTxtFieldFocusGained

    private void registerFirstNameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFirstNameTxtFieldFocusLost
        // TODO add your handling code here:
        if (registerFirstNameTxtField.getText().equals("")) {
            registerFirstNameTxtField.setText("Enter First Name");
            registerFirstNameTxtField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_registerFirstNameTxtFieldFocusLost

    private void registerLastNameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLastNameTxtFieldFocusGained
        // TODO add your handling code here:
        if (registerLastNameTxtField.getText().equals("Enter Last Name")) {
            registerLastNameTxtField.setText("");
            registerLastNameTxtField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_registerLastNameTxtFieldFocusGained

    private void registerLastNameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerLastNameTxtFieldFocusLost
        // TODO add your handling code here:
        if (registerLastNameTxtField.getText().equals("")) {
            registerLastNameTxtField.setText("Enter Last Name");
            registerLastNameTxtField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_registerLastNameTxtFieldFocusLost

    private void loginUserTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserTxtFieldFocusGained
        // TODO add your handling code here:
        if (loginUserTxtField.getText().equals("Enter Username")) {
            loginUserTxtField.setText("");
            loginUserTxtField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_loginUserTxtFieldFocusGained

    private void loginUserTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserTxtFieldFocusLost
        // TODO add your handling code here:
        if (loginUserTxtField.getText().equals("")) {
            loginUserTxtField.setText("Enter Username");
            loginUserTxtField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_loginUserTxtFieldFocusLost

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String registerUsername = registerUserTxtField.getText();
        String registerPassword = registerPasswordTxtField.getText();
        String registerFirstName = registerFirstNameTxtField.getText();
        String registerLastName = registerLastNameTxtField.getText();
        myObj.regUser(registerUsername, registerPassword, registerFirstName, registerLastName);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String loginUsername = loginUserTxtField.getText();
        String loginPassword = loginPasswordPswField.getText();
        String loginMessage = myObj.returnLogin(loginUsername, loginPassword);
        JOptionPane.showMessageDialog(this, loginMessage, "Login Result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_loginBtnActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bckRegisterLP;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLayeredPane loginPasswordLP;
    private javax.swing.JPasswordField loginPasswordPswField;
    private javax.swing.JLabel loginPasswordTxtField;
    private javax.swing.JLabel loginTitleLbl;
    private javax.swing.JLayeredPane loginUserLP;
    private javax.swing.JLabel loginUserLbl;
    private javax.swing.JTextField loginUserTxtField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLayeredPane registerFirstNameLP;
    private javax.swing.JTextField registerFirstNameTxtField;
    private javax.swing.JLayeredPane registerLastNameLP;
    private javax.swing.JTextField registerLastNameTxtField;
    private javax.swing.JLayeredPane registerPasswordLP;
    private javax.swing.JTextField registerPasswordTxtField;
    private javax.swing.JLabel registerTitleLbl;
    private javax.swing.JLayeredPane registerUserLP;
    private javax.swing.JTextField registerUserTxtField;
    // End of variables declaration//GEN-END:variables
}
